### ISSUE TITLE
请教多标签的问题

### ISSUE THREAD

**Issue by XuanxuanGao** [zheng-yuwei/PyTorch-Image-Classification#1]
感谢提供这么完整的代码，从中学到了很多PyTorch的使用方法。
读完整个代码后，我对多标签有点疑惑，这里从数据加载到decode_to_onehot的实现，好像都是只支持一张图片只有一个label的情况，仅仅是loss用的多标签的loss。如果一张图片真的是有多个label，是不是要重写Dataset和decode_to_onehot？

**Comment by zheng-yuwei** [comment]
嗯，是的~

**Comment by XuanxuanGao** [comment]
好的好的～感谢
